spring.application.name=sociale-service
server.port=8081
spring.config.import=optional:configserver:http://localhost:9999
management.endpoints.web.exposure.include=info, refresh, health


spring.cloud.circuitbreaker.bulkhead.resilience4j.enabled=true
resilience4j.retry.instances.retrySearchUtilisateur.max-attempts=4
resilience4j.retry.instances.retrySearchUtilisateur.wait-duration=5s

spring.cache.type=simple


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.1.49:8080/realms/teranga_realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://192.168.1.49:8080/realms/teranga_realm/protocol/openid-connect/certs
