spring.application.name=utilisateur-service
server.port=8090
spring.jpa.hibernate.ddl-auto=update
spring.config.import=optional:configserver:http://localhost:9999
management.endpoints.web.exposure.include=info, refresh, health
logging.level.org.springframework.web=debug


jwt.secret=TerangaConnect2024


spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/teranga_realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/teranga_realm/protocol/openid-connect/certs



