spring.application.name=gateway-service
spring.cloud.discovery.enabled=true
eureka.instance.prefer-ip-address=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
server.port=8898

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/teranga_realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/teranga_realm/protocol/openid-connect/certs
